# Generated by Django 4.2.10 on 2026-01-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_shuffle_questions_alter_exam_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_adaptive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_offline_capable',
            field=models.BooleanField(default=False),
        ),
    ]
