# Generated by Django 4.2.10 on 2026-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_is_adaptive_exam_is_offline_capable'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='negative_marking',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='exam',
            name='partial_scoring',
            field=models.BooleanField(default=False),
        ),
    ]
