# Generated by Django 4.2.10 on 2026-01-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='end_time',
            new_name='finish_time',
        ),
        migrations.AddField(
            model_name='attempt',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='violation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
