# Generated by Django 4.2.10 on 2026-01-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_rename_end_time_attempt_finish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
