# Generated by Django 4.2.10 on 2026-01-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_studentanswer_answer_text_studentanswer_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='marks_awarded',
            field=models.FloatField(default=0.0),
        ),
    ]
