# Generated by Django 4.2.10 on 2026-01-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('DESCRIPTIVE', 'Descriptive / Essay')], max_length=20),
        ),
    ]
